export const DISCLAIMER_HEADING = 'Important context';

export const DEFAULT_DISCLAIMER_TEXT =
  "This text was generated by AI and edited by humans. It is based on SERL's research publications between January 2020 and September 2025. For technical questions, please contact michael.unterkalmsteiner@bth.se.";

export function resolveDisclaimer(override?: string): string {
  if (override && override.trim().length > 0) {
    return override.trim();
  }

  return DEFAULT_DISCLAIMER_TEXT;
}
